repositories {
    mavenLocal()
    mavenCentral()
    maven { // Anvil Lib
        name = "Cjsah Maven"
        url = "https://server.cjsah.net:1002/maven/"
    }
    maven { // Modrinth File, LazyDFU, Jade
        name = "Modrinth Maven"
        url = "https://api.modrinth.com/maven"
        content {
            includeGroup "maven.modrinth"
        }
    }
    maven { // JEI
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
        content {
            includeGroup "mezz.jei"
        }
    }
    maven { // LDLib2
        url = "https://maven.firstdark.dev/snapshots"
    }
}
