dependencies {
    // Registrate
    api(libs.registrate)

    // AnvilCraft
    implementation(libs.anvilCraft) { transitive = false }
    interfaceInjectionData(libs.anvilCraft) { transitive = false }

    // AnvilLib
    runtimeOnly(libs.anvillib)
    compileOnly(libs.anvillibConfig)
    compileOnly(libs.anvillibRecipe)
    interfaceInjectionData(libs.anvillibRecipe)
    compileOnly(libs.anvillibMoveableEntityBlock)
    interfaceInjectionData(libs.anvillibMoveableEntityBlock)
    compileOnly(libs.anvillibIntegration)

    // JEI
    compileOnlyApi(libs.jeiCommonApi) { transitive = false }
    compileOnlyApi(libs.jeiForgeApi) { transitive = false }
    implementation(libs.jeiForgeImpl) { transitive = false }

    // Jade
    implementation(libs.jade)

    // GuideME
    compileOnly("org.appliedenergistics:guideme:${libs.versions.guideme.get()}:api")
    implementation(libs.guideme)

    // AE2
    runtimeOnly(libs.ae2)

    // Mixin Hotswap Agent(神秘mixin热重载)
    additionalRuntimeClasspath(libs.mixinHotswap)
}
