@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package me.theabab2333.headtap.entity;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;