@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package me.theabab2333.headtap.integration.jade;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;